# -*- coding: utf-8 -*-
"""TweepyTests.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pY-kwvap4L9TPK6B3yPFG0208aimNe2s
"""

import tweepy as tw
import pandas as pd

with open('to-do.txt', 'r') as tfile:
    consumer_key = tfile.readline().strip('\n')
    consumer_secret = tfile.readline().strip('\n')
    access_token = tfile.readline().strip('\n')
    access_token_secret = tfile.readline().strip('\n')

auth = tw.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tw.API(auth)

tw_keys = tweet._json.keys()

tw_dict = {}
tw_dict = tw_dict.fromkeys(tw_keys)

#public_tweets = api.home_timeline()
search_words = 'ENEM' + '-filter:retweets'
public_tweets = tw.Cursor(api.search,q=search_words).items(15)

for key in tw_dict.keys():
    try:
        tw_keys = tweet._json[key]
        tw_dict[key].append(tw_keys)
    except KeyError:
        tw_keys = ''
        tw_dict[key].append('')
    except:
        tw_dict[key] = [tw_keys]
    print("tw__dict[key]: {} - tweet[key]: {}".format(tw_dict[key], tw_keys))

df_tweets = pd.DataFrame.from_dict(tw_dict)

df_tweets